In [3]:
import numpy as np

In [9]:
myarr = np.array([[3,6,45,7]], np.int8)

In [10]:
myarr[0,1]

6

In [11]:
myarr.shape

(1, 4)

In [12]:
myarr.dtype

dtype('int8')

In [13]:
myarr[0,1] =45

In [14]:
myarr

array([[ 3, 45, 45,  7]], dtype=int8)

## Array creation: Conversion from other python structures 

In [15]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [16]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [17]:
listarray.dtype

dtype('int32')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [22]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [23]:
zeros = np.zeros((2,5))

In [24]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
rng = np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
lspace = np.linspace(1,5,4) # space

In [35]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [36]:
emp = np.empty((4,6))

In [37]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37960147e-306, 1.33511562e-306, 2.22518251e-306,
        1.33511969e-306, 1.78022342e-306, 1.05700345e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.33511562e-306, 1.24610383e-306],
       [1.69118108e-306, 1.69111725e-306, 1.69118923e-306,
        1.11260144e-306, 6.89812281e-307, 2.22522596e-306]])

In [38]:
emp_like = np.empty_like(lspace)

In [39]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [41]:
ide = np.identity(45)

In [42]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [43]:
ide.shape

(45, 45)

In [46]:
arr = np.arange(99)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr = arr.reshape(3,33)

In [51]:
arr = arr.ravel() #convert in one-d array

In [53]:
arr.shape

(99,)

In [58]:
x = [[1,2,3],[4,5,6],[7,8,10]]

In [59]:
ar = np.array(x)

In [61]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [60]:
ar.sum(axis=0) #sum of axis

array([12, 15, 19])

In [62]:
ar.sum(axis=1)

array([ 6, 15, 25])

In [63]:
ar.T #transpose

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6, 10]])

In [64]:
ar.flat

In [65]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
10


In [66]:
ar.ndim

2

In [67]:
ar.size

9

In [68]:
ar.nbytes

36

In [69]:
one = np.array([1,3,4,673,4])

In [70]:
one.argmax()

3

In [71]:
one.argmin()

0

In [72]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [73]:
ar

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [76]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [75]:
ar.argmax()

8

In [77]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [78]:
ar2 = np.array([[ 1,  2,  1],
       [ 4,  0,  6],
       [ 1,  8, 10]])

In [79]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [ 8, 16, 20]])

In [80]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.16227766]])

In [81]:
ar.sum()

46

In [82]:
ar.max()

10

In [83]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [84]:
np.count_nonzero(ar)

9

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [86]:
import sys

In [92]:
py_ar = [0,4,55,2]

In [93]:
np_arr = np.array(py_ar)

In [94]:
sys.getsizeof(1) * len(py_ar)

112

In [96]:
np_arr.itemsize * np_arr.size

16